name: first_flutter_app
description: First Flutter application.

dependencies:
  flutter:
    sdk: flutter

  english_words: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
